# NB: This file assumes you have already run "map by school 1 (setup).R"

################################
## Second set: tag as percentage of school total as radii, each tag separately
##
filename <- paste0(imageloc, "US map, percent case 2001-2010, N",diss.count,".pdf")
pdf(filename)
map("worldHires",c("usa","Canada","Mexico"), xlim=c(-135,-53), ylim=c(23,58), fill=FALSE)
map("state", boundary = FALSE, col="gray",add=TRUE)
points(x=Lng[case],y=Lat[case],cex=sqrt(Case.sum/DissCount),col="gray10",pch=21,bg=mycol)
title("Clinical / Case Study dissertations \n as percentage of school total", sub=paste(casesum, "dissertations, 2001-2010"))
dev.off()

filename <- paste0(imageloc, "US map, percent crit 2001-2010, N",diss.count,".pdf")
pdf(filename)
map("worldHires",c("usa","Canada","Mexico"), xlim=c(-135,-53), ylim=c(23,58), fill=FALSE)
map("state", boundary = FALSE, col="gray",add=TRUE)
points(x=Lng[crit],y=Lat[crit],cex=sqrt(Crit.sum/DissCount),col="gray10",pch=21,bg=mycol)
title("Critical / Hermeneutical dissertations \n as percentage of school total", sub=paste(critsum, "dissertations, 2001-2010"))
dev.off()

filename <- paste0(imageloc, "US map, percent cult 2001-2010, N",diss.count,".pdf")
pdf(filename)
map("worldHires",c("usa","Canada","Mexico"), xlim=c(-135,-53), ylim=c(23,58), fill=FALSE)
map("state", boundary = FALSE, col="gray",add=TRUE)
points(x=Lng[cult],y=Lat[cult],cex=sqrt(Cult.sum/DissCount),col="gray10",pch=21,bg=mycol)
title("Cultural-Critical dissertations \n as percentage of school total", sub=paste(cultsum,"dissertations, 2001-2010"))
dev.off()

filename <- paste0(imageloc, "US map, percent disc 2001-2010, N",diss.count,".pdf")
pdf(filename)
map("worldHires",c("usa","Canada","Mexico"), xlim=c(-135,-53), ylim=c(23,58), fill=FALSE)
map("state", boundary = FALSE, col="gray",add=TRUE)
points(x=Lng[disc],y=Lat[disc],cex=sqrt(Disc.sum/DissCount),col="gray10",pch=21,bg=mycol)
title("Discourse or Text Analysis dissertations \n as percentage of school total", sub=paste(discsum,"dissertations, 2001-2010"))
dev.off()

filename <- paste0(imageloc, "US map, percent ethn 2001-2010, N",diss.count,".pdf")
pdf(filename)
map("worldHires",c("usa","Canada","Mexico"), xlim=c(-135,-53), ylim=c(23,58), fill=FALSE)
map("state", boundary = FALSE, col="gray",add=TRUE)
points(x=Lng[ethn],y=Lat[ethn],cex=sqrt(Ethn.sum/DissCount),col="gray10",pch=21,bg=mycol)
title("Ethnographic dissertations \n as percentage of school total", sub=paste(ethnsum,"dissertations, 2001-2010"))
dev.off()

filename <- paste0(imageloc, "US map, percent expt 2001-2010, N",diss.count,".pdf")
pdf(filename)
map("worldHires",c("usa","Canada","Mexico"), xlim=c(-135,-53), ylim=c(23,58), fill=FALSE)
map("state", boundary = FALSE, col="gray",add=TRUE)
points(x=Lng[expt],y=Lat[expt],cex=sqrt(Expt.sum/DissCount),col="gray10",pch=21,bg=mycol)
title("Experimental dissertations \n as percentage of school total", sub=paste(exptsum,"dissertations, 2001-2010"))
dev.off()

filename <- paste0(imageloc, "US map, percent hist 2001-2010, N",diss.count,".pdf")
pdf(filename)
map("worldHires",c("usa","Canada","Mexico"), xlim=c(-135,-53), ylim=c(23,58), fill=FALSE)
map("state", boundary = FALSE, col="gray",add=TRUE)
points(x=Lng[hist],y=Lat[hist],cex=sqrt(Hist.sum/DissCount),col="gray10",pch=21,bg=mycol)
title("Historical / Archival dissertations \n as percentage of school total", sub=paste(histsum,"dissertations, 2001-2010"))
dev.off()

filename <- paste0(imageloc, "US map, percent intv 2001-2010, N",diss.count,".pdf")
pdf(filename)
map("worldHires",c("usa","Canada","Mexico"), xlim=c(-135,-53), ylim=c(23,58), fill=FALSE)
map("state", boundary = FALSE, col="gray",add=TRUE)
points(x=Lng[intv],y=Lat[intv],cex=sqrt(Intv.sum/DissCount),col="gray10",pch=21,bg=mycol)
title("Interview / Questionnaire dissertations \n as percentage of school total", sub=paste(intvsum,"dissertations, 2001-2010"))
dev.off()

filename <- paste0(imageloc, "US map, percent meta 2001-2010, N",diss.count,".pdf")
pdf(filename)
map("worldHires",c("usa","Canada","Mexico"), xlim=c(-135,-53), ylim=c(23,58), fill=FALSE)
map("state", boundary = FALSE, col="gray",add=TRUE)
points(x=Lng[meta],y=Lat[meta],cex=sqrt(Meta.sum/DissCount),col="gray10",pch=21,bg=mycol)
title("Meta-Analytical / Discipliniographic dissertations \n as percentage of school total", sub=paste(metasum,"dissertations, 2001-2010"))
dev.off()

filename <- paste0(imageloc, "US map, percent modl 2001-2010, N",diss.count,".pdf")
pdf(filename)
map("worldHires",c("usa","Canada","Mexico"), xlim=c(-135,-53), ylim=c(23,58), fill=FALSE)
map("state", boundary = FALSE, col="gray",add=TRUE)
points(x=Lng[modl],y=Lat[modl],cex=sqrt(Modl.sum/DissCount),col="gray10",pch=21,bg=mycol)
title("Model-Building dissertations \n as percentage of school total", sub=paste(modlsum,"dissertations, 2001-2010"))
dev.off()

filename <- paste0(imageloc, "US map, percent phil 2001-2010, N",diss.count,".pdf")
pdf(filename)
map("worldHires",c("usa","Canada","Mexico"), xlim=c(-135,-53), ylim=c(23,58), fill=FALSE)
map("state", boundary = FALSE, col="gray",add=TRUE)
points(x=Lng[phil],y=Lat[phil],cex=sqrt(Phil.sum/DissCount),col="gray10",pch=21,bg=mycol)
title("Philosophical dissertations \n as percentage of school total", sub=paste(philsum,"dissertations, 2001-2010"))
dev.off()

filename <- paste0(imageloc, "US map, percent poet 2001-2010, N",diss.count,".pdf")
pdf(filename)
map("worldHires",c("usa","Canada","Mexico"), xlim=c(-135,-53), ylim=c(23,58), fill=FALSE)
map("state", boundary = FALSE, col="gray",add=TRUE)
points(x=Lng[poet],y=Lat[poet],cex=sqrt(Poet.sum/DissCount),col="gray10",pch=21,bg=mycol)
title("Poetic / Fictive dissertations \n as percentage of school total", sub=paste(poetsum,"dissertations, 2001-2010"))
dev.off()

filename <- paste0(imageloc, "US map, percent pract 2001-2010, N",diss.count,".pdf")
pdf(filename)
map("worldHires",c("usa","Canada","Mexico"), xlim=c(-135,-53), ylim=c(23,58), fill=FALSE)
map("state", boundary = FALSE, col="gray",add=TRUE)
points(x=Lng[pract],y=Lat[pract],cex=sqrt(Pract.sum/DissCount),col="gray10",pch=21,bg=mycol)
title("Practitioner / Teacher Research dissertations \n as percentage of school total", sub=paste(practsum,"dissertations, 2001-2010"))
dev.off()

filename <- paste0(imageloc, "US map, percent rhet 2001-2010, N",diss.count,".pdf")
pdf(filename)
map("worldHires",c("usa","Canada","Mexico"), xlim=c(-135,-53), ylim=c(23,58), fill=FALSE)
map("state", boundary = FALSE, col="gray",add=TRUE)
points(x=Lng[rhet],y=Lat[rhet],cex=sqrt(Rhet.sum/DissCount),col="gray10",pch=21,bg=mycol)
title("Rhetorical Analysis dissertations \n as percentage of school total", sub=paste(rhetsum,"dissertations, 2001-2010"))
dev.off()

filename <- paste0(imageloc, "US map, percent surv 2001-2010, N",diss.count,".pdf")
pdf(filename)
map("worldHires",c("usa","Canada","Mexico"), xlim=c(-135,-53), ylim=c(23,58), fill=FALSE)
map("state", boundary = FALSE, col="gray",add=TRUE)
points(x=Lng[surv],y=Lat[surv],cex=sqrt(Surv.sum/DissCount),col="gray10",pch=21,bg=mycol)
title("Survey dissertations \n as percentage of school total", sub=paste(survsum,"dissertations, 2001-2010"))
dev.off()

filename <- paste0(imageloc, "US map, percent othr 2001-2010, N",diss.count,".pdf")
pdf(filename)
map("worldHires",c("usa","Canada","Mexico"), xlim=c(-135,-53), ylim=c(23,58), fill=FALSE)
map("state", boundary = FALSE, col="gray",add=TRUE)
points(x=Lng[othr],y=Lat[othr],cex=sqrt(Othr.sum/DissCount),col="gray10",pch=21,bg=mycol)
title("Other dissertations \n as percentage of school total", sub=paste(othrsum,"dissertations, 2001-2010"))
dev.off()

