##
# Overview of analyses 
# This file is a run-down of the programs that could re-create my figures from prepared data.
# For initial data cleaning, I used GoogleRefine (now OpenRefine); see files in the OpenRefine directory.


# Set working directory to the location of R script files.
setwd("/Users/benmiller314/Dropbox/coursework, etc/dissertation/data, code, and figures/Dissertation Research")

## 
# Global variables called in many functions.
# remake_figs: If TRUE, save new files for figures; if FALSE, display on screen only.
# autorun: If TRUE, call the functions when files are sourced; if FALSE, load functions but do not call.
remake_figs <- FALSE; 
autorun <- FALSE;

## 
# `dataprep`: prepares working environment by loading helper functions and setting key variables (such as tagset).
# `dataprep 2`: loads in a .csv file of tagged spreadsheet data, generates a tag array, and defines various subsets.
# 	You will be prompted to select the file via file.choose().
# NB: These two functions can be called jointly via source(file="start here.R")
source(file="dataprep.R")
source(file="dataprep 2 - load data.R")

## 
# `tags by school`: generates heat plots of methods used in dissertations, aggregated by school.
# 	Provides two functions:
#	schoolwise.data(dataset_name, tagset_name): returns a list of tag means, sums, and counts,
#		each aggregated by school.
#	schoolwise(dataset_name, tagset_name, ...): make one or more heatplots from the output of schoolwise.data().
source(file="tags by school.R")

## 
# `methodcount barplot`: produces a bar plot of method-tag counts per dissertation, for a given method tagset.
# `keyword barplot`: produces a bar plot of author-provided keyword-tag counts per dissertation. Not so useful.
source(file="methodcount barplot.R")
# source(file="keyword barplot.R")

## 
# `frequency of method tags`: tabulates and plots the number of times a dissertation is tagged with each method.
# Provides three functions:
#	get_tags(dataset_name, tagset_name): returns a named vector of frequencies for each method in the tagset
#	methodfreq_combined(bigset, smallset, diffset): plots an overlaid horizontal bar graph of method frequencies;
#		by default the three sets are noexcludes, consorts, and nonconsorts, respectively (but others are possible).
# 	compare_method_ranks(set1, set2, ...): creates a side-by-side plot of methods in descending rank order, 
#		with lines connecting the same methods to quickly reveal changes in rank.
source(file="frequency of method tags.R")


## 
# `top schools by method.R`: For each method in a given tagset, produce a list of the top X schools by either 
#	methodological output (number of dissertations using that method at that school) or methodological focus 
#	(percentage of dissertations using that method at that school).
#	Provides one function: toplists(dataset_name, tagset_name, howmany, threshold, since, until, rank_by_pcts, combine)
source(file="top schools by method.R")	


## 
# `collocation heatmap`: If a dissertation is tagged X, how many times is it also tagged Y? Aggregates methods tags
# by other methods tags, with an option to norm by dividing the sums by each method's total count. 
# Optionally plots a heatmap of results as an adjacency matrix. Requires `ben_heatmap.R`.
source(file="collocation heatmap.R")

# `schools per year`: for each year, finds the number of institutions and number of dissertations.
# Optionally plots these numbers as a line graph
source(file="schools per year.R") 

# source(file="map by school.R")		# per-method maps	# look for the individual files instead
source(file="map by school 4 (comp-rhet superimposed on carnegie schools).R")

## Topic Modeling functions
source(file="r2mallet with foreach.R")				# generate a (series of) topic model(s)
source(file="top docs per topic.R")					# browse topics to generate labels
source(file="get topics for author.R")				# retrieve topic information about a dissertation by author name
source(file="cotopics.R")							# find topics that co-occur within documents
source(file="get doctopic grid.R")					# get weights of every topic for all documents

##
# frameToD3: outputs JSON file of topic model data for interactive visualizations.
# provides two functions:
#	frameToJSON(dataset_name, ntopics, do.plot, groupVars, dataVars, outfile, bad.topics): given a topic model as generated by 'r2mallet with foreach.R', returns a hierarchical clustering of topics in JSON. For each topic, includes the following metadata: name, size, scaledsize, topwords, topic, rank.
#	cotopic_edges(dataset_name, ntopics, level, min, outfile, bad.topics): given a topic model as generated by 'r2mallet with foreach.R', returns weighted edges between topics and the same hierarchical clustering as above. 
source(file="frameToD3.R")							

source(file="topics by year.R")						# rank topics overall, aggregated per year
source(file="variation of topic proportions.R")		# distribution of topic strength for all documents' top 10 topics 
source(file="single topic strength vs rank.R")		# are overall top topics high-ranked in few documents, or evenly spread?

