source(file="dataprep.R")
remake_figs <- TRUE; source(file="tags by school.R")
source(file="methodcount barplot.R")
source(file="keyword barplot.R")
source(file="collocation heatmap.R")
source(file="map by school 4 (comp-rhet superimposed on carnegie schools).R")
source(file="top 10 lists.R")
# source(file="map by school.R")		# per-method maps
source(file="schools per year.R") 
