#!/bin/bash                             # declare our shell environment


# Where are the fulltext files (from ProQuest) and the index files (from R)?
SRC=~/'Documents/fulltext_dissertations'
DST_ROOT=~/'Box Sync/research/firstpages'
INDEX_DIR=~/'Dropbox/coursework, etc/dissertation/data, code, and figures/Dissertation Research/Shell scripts and commands'

if ! [ -d "$DST_ROOT" ] ; then
	printf "Creating destination folder $4 ..."
	mkdir "$DST_ROOT"
	if [ $? = 0 ] ; then echo "Done." ; fi
fi

# Let's move, but come back at the end
CURRENT_DIR="$PWD"
cd "$SRC"

# Extract from pdf starting and ending on which pages?
STARTPAGE=1
ENDPAGE=22

# Function to extract pages from a pdf file, via 
# http://www.linuxjournal.com/content/tech-tip-extract-pages-pdf
function pdf_extract()
{
    # this function uses 4 arguments:
    #     $1 is the first page of the range to extract
    #     $2 is the last page of the range to extract
    #     $3 is the input file, ending in .PDF
    #     $4 is the target directory
    #     output file will be named "./target_dir/inputfile_pXX-pYY.pdf"


	if ! [ -d "$4" ] ; then
		printf "Creating destination folder $4 ..."
		mkdir "$4"
		if [ $? = 0 ] ; then echo "Done." ; fi
	fi

#    echo $4/${3%.PDF}_p${1}-p${2}.pdf
    gs -sDEVICE=pdfwrite -dNOPAUSE -dBATCH -dSAFER \
       -dFirstPage=${1} \
       -dLastPage=${2} \
       -sOutputFile="$4/${3%.PDF}_p${1}-p${2}.pdf" \
       ${3}
}

# Function to convert Pub.numbers from the file into proper filenames, 
# then copy the file. Calls pdf_extract(), defined above.
function subset_firstpages
{
	# Make sure we have a place to copy the files to.
	DST="$DST_ROOT/$1_only"
	if ! [ -d "$DST" ] ; then
		printf "Creating destination folder $4 ..."
		mkdir "$DST"
		if [ $? = 0 ] ; then echo "Done." ; fi
	fi
# 	ls "$DST"

	# Get the list of file numbers (generated by 'dataprep 2 - load data.R')
	# Convert file numbers to proper filenames, and copy to destination folder.
	j=0; k=0									# reset counters
	while read i; do							# start the loop
		FILE="$i.PDF"
# 		printf "FILE is $FILE, in dir $PWD\n"
		printf "Copying $FILE to folder for $1 files only... "
		pdf_extract $STARTPAGE $ENDPAGE $FILE "$DST"
		if [ $? = 0 ] ; then 					# did it work? if so,
			echo "Done." 						# report back, and
			j=$((j+1))							# increment the counter.
		fi
		k=$((k+1))
	done < "$INDEX_DIR/file list $1.txt"		# draw `i` from the file
												# (each line is one input)
	
	echo "Copied $j of $k files."				# final status report.
}

# Call the function. Change the value after the command to change the subset.
subset_firstpages realconsorts

# and go back to the calling directory, as promised
cd "$CURRENT_DIR"