#!/bin/bash											# declare our shell environment

## Strategy: read in a textfile indexing various data subsets as output by R. 
## While items remain in the list, copy that subset to a new directory 
## to make analysis easier in AntConc and Mallet.

# Where are the cleaned files (output by ben_clean_and_consolidate.sh)?
SRC='/Users/benmiller314/Documents/fulltext dissertations/clean'

# Where are the index files (from R)?
INDEX_DIR='/Users/benmiller314/Dropbox/coursework, etc/dissertation/R experiments/Dissertation Research/Shell scripts and commands'


# Function to convert Pub.numbers from the file into proper filenames, then copy the file
function subset_copy
{
	# Make sure we have a place to copy the files to.
	DST="$SRC/../clean_$1_only"
# 	ls "$DST"

	if ! [ -d "$DST" ] ; then
		printf "Creating destination folder $DST ..."
		mkdir "$DST"
		if [ $? = 0 ] ; then echo "Done." ; fi
	fi

	# Get the list of file numbers (generated by 'dataprep 2 - load data.R'
	# Convert file numbers to proper filenames, and copy to destination folder.
	j=0; k=0													# reset counters
	while read i; do											# start the loop
		FILE="cleaned_$i.txt"
		printf "Copying $FILE to folder for $1 files only... "
		cp "$SRC/$FILE" "$DST/$FILE"
		if [ $? = 0 ] ; then 									# did it work? if so,
			echo "Done." 										# report back, and
			j=$((j+1))											# increment the counter.
		fi
		k=$((k+1))
	done < "$INDEX_DIR/file list $1.txt"						# draw `i` from the file
																# (each line is one input)
	
	echo "Copied $j of $k files."								# final status report.
}

# subset_copy consorts
# subset_copy nonconsorts
subset_copy noexcludes
